#!/bin/bash
# Exemple d'utilisation du système de diarisation

echo "📖 Exemple d'utilisation du système de diarisation"
echo ""
echo "1. Activer l'environnement virtuel:"
echo "   source venv/bin/activate"
echo ""
echo "2. Se connecter à HuggingFace (première fois seulement):"
echo "   huggingface-cli login"
echo "   Puis accepter les conditions sur:"
echo "   https://huggingface.co/pyannote/speaker-diarization-3.1"
echo ""
echo "3. Placer vos fichiers audio dans audio_input/"
echo "   Exemple:"
echo "   - audio_input/presentateur.wav"
echo "   - audio_input/invite.wav"
echo ""
echo "4. Lancer la diarisation:"
echo "   python main.py \\"
echo "       --presentateur audio_input/presentateur.wav \\"
echo "       --invite audio_input/invite.wav \\"
echo "       --output results/diarisation.txt"
echo ""
echo "5. Consulter les résultats dans results/diarisation.txt"
echo ""
echo "💡 Astuce: Le système fonctionne avec n'importe quelle langue!"
